server:
  port: 8037

spring:
 #REDIS CONFIG
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:8777}    #6379
      password: ${REDIS_PASSWORD:}
      connect-timeout: 2000ms # No esperar más de 2s para conectar
      timeout: 500ms         # No esperar más de 500ms por una respuesta (Redis debe ser rápido)
      lettuce:
        pool:
          max-active: 8      # Número máximo de conexiones simultáneas
          max-idle: 8        # Conexiones en espera

  application:
    name: "hexagonal-loan-service"

  datasource:
    url: "jdbc:postgresql://localhost:9091/loan_db"
    username: "jcvidal"
    password: "123456"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: "create"
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 25

  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    default-property-inclusion: "non_null"
  web:
    error:
      include-message: "always"
      include-binding-errors: "always"

logging:
  level:
    root: "INFO"
    com.jorgeluis.mascotienda: "DEBUG"